project:
  type: website
  output-dir: docs

website:
  title: "practice_quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects_and_publications.qmd

format:
  html:
    theme:
      light: sandstone
      dark: solar
    css: styles.css
    toc: true

editor: visual

