project:
  type: website
  output-dir: docs

website: 
  title: "Isaac Rosenthal"
  navbar:
    right:
      - text: "About Me"
        href: about.qmd
      - text: "Projects and Publications"
        href: projects_and_publications.qmd
      - text: "Resume"
        href: files/documents/Rosenthal_CV.pdf
      - icon: github
        href: https://github.com/Irosenthal/Irosenthal_quarto_site

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual